### ISSUE TITLE
Negative Values in Icinga

### ISSUE THREAD

**Issue by davidak** [mclarkson/check_iftraffic_nrpe.sh#2]
First of all thanks for this Plugin!

It returns the right Values:
```
/usr/local/icinga/libexec/check_nrpe -H 10.101.32.64 -c check_iftraffic
OK: See graphs for stats. | in-eth0=2688315 out-eth0=7614391 in-eth1=6808 out-eth1=1957 in-eth2=708 out-eth2=0 in-eth3=0 out-eth3=0 in-eth4=708 out-eth4=0 in-eth5=708 out-eth5=0 in-eth6=708 out-eth6=0 in-eth7=0 out-eth7=0 in-xenbr0=269163 out-xenbr0=5585000 in-xenbr2=648 out-xenbr2=0 in-xenbr3=0 out-xenbr3=0 in-xenbr5=648 out-xenbr5=0 in-xenbr7=0 out-xenbr7=0 in-xenbr4=648 out-xenbr4=0 in-xenbr6=648 out-xenbr6=0 in-xenbr1=4763 out-xenbr1=0
```

But Icinga saves some negative values in the RDD:

```
rrdtool fetch /usr/local/pnp4nagios/var/perfdata/srv27/iftraffic.rrd MIN
[...] 2.4188777810e+06 -1.2447015286e+06 1.2816928571e+03 0.0000000000e+00 1.2818190476e+03 0.0000000000e+00 1.2825666667e+03 0.0000000000e+00 4.8271904762e+02 0.0000000000e+00 4.8271904762e+02 0.0000000000e+00 4.8271904762e+02 0.0000000000e+00 0.0000000000e+00 0.0000000000e+00 1.4396227405e+06 -4.4331384048e+06 1.2465666667e+03
```

And PNP4Nagios displays it like this:

![2014-07-30 12_32_26-service-details srv17 -_ iftraffic - chromium](https://cloud.githubusercontent.com/assets/91113/3747932/041b5be4-17d5-11e4-99b7-8bb94c1d4a92.png)

Have you any Idea where the problem is and how to fix it?

**Comment by davidak** [comment]
any progress here?

**Comment by mclarkson** [comment]
I can't remember whether checking for rollover was a simple, quick code change, or not. I'll take another look, probably this weekend, but I'd also happily accept a PR 😉

**Comment by mclarkson** [comment]
Sorry but it's going to take me a little while to do this, but now I know someone [really] wants it (@davidak) I've put it on my todo list. In fact, I've just reread this issue and see that for you (and that must mean others too) the rollover calculation should fix the last minus values.

For me, or anyone else - implement this:
```
#added 20050414 by mw
#This function detects if an overflow occurs. If so, it returns
#a computed value for $bytes.
#If there is no counter overflow it simply returns the origin value of $bytes.
#IF there is a Counter reboot wrap, just use previous output.
sub counter_overflow {
    my ( $bytes, $last_bytes, $max_bytes ) = @_;

    $bytes += $max_bytes if ( $bytes < $last_bytes );
    $bytes = $last_bytes  if ( $bytes < $last_bytes );
    return $bytes;
}
```

**Comment by davidak** [comment]
here is the function in bash:

```
function correct_overflow {
	bytes=$1 ; last_bytes=$2 ; max_bytes=$3
	if [[ $bytes -lt $last_bytes ]] ; then let "bytes += $max_bytes" ; fi
	if [[ $bytes -lt $last_bytes ]] ; then bytes=$last_bytes ; fi
	echo $bytes
}

correct_overflow 10 20 50
60
```

can you test the 3 cases with real values and integrate it?

**Comment by davidak** [comment]
@mclarkson can you test my code and integrate it at the right place?

**Comment by mclarkson** [comment]
I don't really have time :( If you could implement and test I would be happy to accept a Pull Request.

**Comment by davidak** [comment]
OK. I have integrated it, but it doesn't work (every time).

https://github.com/davidak/check_iftraffic_nrpe.sh/commit/6f73299e2f0553b6b1354b2fb2a914872c31dee7

i have commented out your `minus_values` to see if it helps. we have still a lot of negative values.

(since my last comments we have migrated to icinga 2 and grafana instead of pnp4nagios. icinga2 is much more performant than 1 ;) the checks run every minute now!)

![bildschirmfoto vom 2015-07-10 14 58 14](https://cloud.githubusercontent.com/assets/91113/8619215/530c7454-2715-11e5-8f34-1d28a49404f0.png)

`rx1` and `tx1` doesn't have data. the actual data seams to be in `${rx[i]}`.

https://github.com/davidak/check_iftraffic_nrpe.sh/blob/master/check_iftraffic_nrpe.sh#L439-L440

What variable is the actual rx and tx data and what is that data from the last check?

![bildschirmfoto vom 2015-07-10 15 40 20](https://cloud.githubusercontent.com/assets/91113/8619813/657c4a4c-271a-11e5-9995-c7e4cc1e5877.png)

**Comment by mclarkson** [comment]
I think you just made a typo - you put 'rx1' but it's 'rxl' (small 'L' for latest)

rx[i] and tx[i] hold the data from the cache, that's the data read the previous time the script ran.

So, current data in rxl/txl, and cached data from last time in rx[i]/tx[i]

Some notes:

Line 11: header: **Append** your two 'modified' lines at the bottom, not insert.

Line 75: variable declarations: Add a new option variable (all uppercase) for rollover checking.

Line 189: usage() func: Add description of new option for rollover checking.

Lines 450-456: Your new code: Surround with an 'if' test for the rollover variable so it only runs if the option is set.

Lines 506-518: Put the minus_values checks back. They will not be run if rollover calculation runs since there won't be any minus values.

**Comment by davidak** [comment]
yeah, now it works! :)

<img width="1254" alt="bildschirmfoto 2015-07-11 um 18 10 47" src="https://cloud.githubusercontent.com/assets/91113/8634430/767f2f92-27f8-11e5-8d9e-f0eb5ab0e5b8.png">

i had the minus_value correction commented out so you see before that change where minus_values (rollovers) and after it none.
