### ISSUE TITLE
WARNING: Interfaces changed. Got first sample, again

### ISSUE THREAD

**Issue by vinod9987** [mclarkson/check_iftraffic_nrpe.sh#8]
On Nagios GUI, every now and then I am getting below warning -

`WARNING: Interfaces changed. Got first sample, again`

I tried running the script locally and I can replicate this, After next consecutive run it goes away, Any idea why this is happening and how can I fix this?

`SERVER ~]# /usr/lib64/nagios/plugins/check_iftraffic_nrpe.sh -x eth* -x lo -x sit0 -s 4 -w 90
WARNING: Interfaces changed. Got first sample, again.`

Next Run
`SERVER tmp]# /usr/lib64/nagios/plugins/check_iftraffic_nrpe.sh -x eth* -x lo -x sit0 -s 4 -w 90 -u
OK: Stats: ppp19(0/0) ppp22(3K/1K) ppp24(58K/6K) ppp25(0/0) ppp26(0/0) ppp27(0/0) ppp1(32K/3K) ppp2(835/417) ppp3(12K/1K) ppp7(11K/1K) ppp8(835/412) ppp10(5K/3K) ppp11(456/786) ppp12(51K/6K) ppp13(2K/1K) ppp14(44K/21K) ppp15(255/1K) ppp4(0/0) ppp28(0/0) ppp29(0/0) ppp30(28K/884) ppp0(436/1K) ppp5(41K/2K) ppp6(761/987) ppp17(276/1K) ppp18(36K/3K) (in/out in bytes/s)`

**Comment by mclarkson** [comment]
Steps to mitigate, one or more of:
- Increase polling frequency.
- Use rollover checking (-r), but realise that this will skew results if it rolls over twice.

Read carefully issue #2

**Comment by vinod9987** [comment]
I am polling every 5 mins, polling more frequently is not possible here for some other reasons. But (-r) did help, I saw this warning only once in about 1 hr after adding (-r), earlier it was multiple times.

Thanks,
Vinod

**Comment by mclarkson** [comment]
You just need to make sure it doesn't roll over twice! Do the math on your max throughput to make sure. Closing.
